title: "Projects.io - Portfolio"
description: "A professional portfolio showcasing projects built with Jekyll and GitHub Pages. This is a Demo for DevOps class"
baseurl: "/projects.io"  # Base URL for your site
url: "https://m-pasima.github.io"  # GitHub Pages URL
theme: jekyll-theme-time-machine  # Default theme

# Social Links
twitter_username: pasima
github_username: m-pasima
linkedin_username: pasima


footer:
  text: "© 2024 m-pasima. All rights reserved."
